#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TARGET="$ROOT/infra/.env.test"

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

if [[ -f "$TARGET" && "$FORCE" != "true" ]]; then
  echo "File already exists: $TARGET"
  echo "Re-run with --force to overwrite."
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate test secrets."
  exit 1
fi

rand_hex() {
  openssl rand -hex "$1"
}

rand_b64() {
  openssl rand -base64 "$1" | tr -d '\r\n'
}

POSTGRES_PASSWORD="$(rand_hex 16)"
REDIS_PASSWORD="$(rand_hex 16)"
JWT_SECRET="$(rand_b64 48)"
TURN_SECRET="$(rand_hex 32)"
MINIO_SECRET_KEY="$(rand_hex 16)"

cat > "$TARGET" <<EOF
# Auto-generated test environment for Seclettr.
# Generated by scripts/gen-test-env.sh
# Do not commit this file.

NODE_ENV=test
HOST=127.0.0.1
PORT=3001

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
JWT_SECRET=$JWT_SECRET
TURN_SECRET=$TURN_SECRET
TURN_DOMAIN=localhost
ALLOW_PUBLIC_REGISTRATION=true

MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=$MINIO_SECRET_KEY

ANNOUNCED_IP=127.0.0.1
CORS_ORIGIN=http://localhost:5173
NGINX_CONFIG=nginx.http.conf

DATABASE_URL=postgresql://seclettr:$POSTGRES_PASSWORD@localhost:5432/seclettr
REDIS_URL=redis://:$REDIS_PASSWORD@localhost:6379

S3_ENDPOINT=http://localhost:9000
S3_BUCKET=seclettr-attachments
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=$MINIO_SECRET_KEY
S3_REGION=us-east-1

SFU_URL=http://localhost:3002

# Optional convenience values for local test runners
API_URL=http://localhost:3001
BASE_URL=http://localhost:5173
EOF

chmod 600 "$TARGET" 2>/dev/null || true
echo "Generated $TARGET"
